Add azure blob support

diff --git a/bin/backup_and_upload b/bin/backup_and_upload
--- a/bin/backup_and_upload
+++ b/bin/backup_and_upload
@@ -33,6 +33,16 @@ case "${provider}" in
     "${dir}" "${gzip}" "${exclude_paths}" "${mark}" \
     "${bucket}" "${destination}" "${max_concurrent_requests}" "${max_bandwidth}" "${storage_class}" "${content_disposition}" "${endpoint_url}"
   ;;
+"azure")
+  if [[ -z "${secret}" ]]; then
+    echo >&2 "Missing Azure storage account key"
+    exit 1
+  fi
+  backup_and_upload_azure \
+    "${dir}" "${gzip}" "${exclude_paths}" "${mark}" \
+    "${key}" "${secret}" "${bucket}" "${destination}" \
+    "${max_concurrent_requests}" "${max_bandwidth}" "${storage_class}" "${content_disposition}" "${endpoint_url}"
+  ;;
 "gcp")
   if [[ ! -f "${key}" ]]; then
     echo "${key}" | base64 -d >/tmp/sa.json
diff --git a/bin/upload b/bin/upload
--- a/bin/upload
+++ b/bin/upload
@@ -29,6 +29,15 @@ case "${provider}" in
   AWS_REGION=${region} AWS_ACCESS_KEY_ID=${key} AWS_SECRET_ACCESS_KEY=${secret} upload_aws \
     "${filepath}" "${bucket}" "${destination}" "${max_concurrent_requests}" "${max_bandwidth}" "${storage_class}" "${content_disposition}" "${endpoint_url}"
   ;;
+"azure")
+  if [[ -z "${secret}" ]]; then
+    >&2 echo "Missing Azure storage account key"
+    exit 1
+  fi
+  upload_azure \
+    "${key}" "${secret}" "${filepath}" "${bucket}" "${destination}" \
+    "${max_concurrent_requests}" "${max_bandwidth}" "${storage_class}" "${content_disposition}" "${endpoint_url}"
+  ;;
 "gcp")
   if [[ ! -f "${key}" ]]; then
     echo "${key}" | base64 -d > /tmp/sa.json
