Add support for s3-compat storages, update alpine

diff --git a/bin/backup_and_upload b/bin/backup_and_upload
--- a/bin/backup_and_upload
+++ b/bin/backup_and_upload
@@ -20,6 +20,7 @@ max_bandwidth=${11}
 storage_class=${12}
 content_disposition=${13}
 region=${14}
+endpoint_url=${15}
 
 case "${provider}" in
 "aws")
@@ -27,9 +28,10 @@ case "${provider}" in
     echo >&2 "Missing AWS secret access key"
     exit 1
   fi
+  storage_class=${storage_class:-STANDARD}
   AWS_REGION=${region} AWS_ACCESS_KEY_ID=${key} AWS_SECRET_ACCESS_KEY=${secret} backup_and_upload_aws \
     "${dir}" "${gzip}" "${exclude_paths}" "${mark}" \
-    "${bucket}" "${destination}" "${max_concurrent_requests}" "${max_bandwidth}" "${storage_class}" "${content_disposition}"
+    "${bucket}" "${destination}" "${max_concurrent_requests}" "${max_bandwidth}" "${storage_class}" "${content_disposition}" "${endpoint_url}"
   ;;
 "gcp")
   if [[ ! -f "${key}" ]]; then
@@ -41,6 +43,16 @@ case "${provider}" in
     "${key}" "${bucket}" "${destination}" "${storage_class}" "${content_disposition}"
   ;;
 *)
-  exit 1
+  if [[ -z "${secret}" ]]; then
+    echo >&2 "Missing S3 secret access key"
+    exit 1
+  fi
+  if [[ -z "${endpoint_url}" ]]; then
+    echo >&2 "Missing S3 endpoint URL"
+    exit 1
+  fi
+  AWS_REGION=${region} AWS_ACCESS_KEY_ID=${key} AWS_SECRET_ACCESS_KEY=${secret} backup_and_upload_aws \
+    "${dir}" "${gzip}" "${exclude_paths}" "${mark}" \
+    "${bucket}" "${destination}" "${max_concurrent_requests}" "${max_bandwidth}" "${storage_class}" "${content_disposition}" "${endpoint_url}"
   ;;
 esac
diff --git a/bin/upload b/bin/upload
--- a/bin/upload
+++ b/bin/upload
@@ -17,6 +17,7 @@ max_bandwidth=$8
 storage_class=$9
 content_disposition=${10}
 region=${11}
+endpoint_url=${12}
 
 case "${provider}" in
 "aws")
@@ -24,8 +25,9 @@ case "${provider}" in
     >&2 echo "Missing AWS secret access key"
     exit 1
   fi
+  storage_class=${storage_class:-STANDARD}
   AWS_REGION=${region} AWS_ACCESS_KEY_ID=${key} AWS_SECRET_ACCESS_KEY=${secret} upload_aws \
-    "${filepath}" "${bucket}" "${destination}" "${max_concurrent_requests}" "${max_bandwidth}" "${storage_class}" "${content_disposition}"
+    "${filepath}" "${bucket}" "${destination}" "${max_concurrent_requests}" "${max_bandwidth}" "${storage_class}" "${content_disposition}" "${endpoint_url}"
   ;;
 "gcp")
   if [[ ! -f "${key}" ]]; then
@@ -35,6 +37,15 @@ case "${provider}" in
   upload_gcp "${key}" "${filepath}" "${bucket}" "${destination}" "${storage_class}" "${content_disposition}"
   ;;
 *)
-  exit 1
+  if [[ -z "${secret}" ]]; then
+    >&2 echo "Missing S3 secret access key"
+    exit 1
+  fi
+  if [[ -z "${endpoint_url}" ]]; then
+    >&2 echo "Missing S3 endpoint URL"
+    exit 1
+  fi
+  AWS_REGION=${region} AWS_ACCESS_KEY_ID=${key} AWS_SECRET_ACCESS_KEY=${secret} upload_aws \
+    "${filepath}" "${bucket}" "${destination}" "${max_concurrent_requests}" "${max_bandwidth}" "${storage_class}" "${content_disposition}" "${endpoint_url}"
   ;;
 esac
